// <auto-generated />
namespace RatiusCommunityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial43));
        
        string IMigrationMetadata.Id
        {
            get { return "201605101239391_initial43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
