// <auto-generated />
namespace RatiusCommunityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class isFirstTimeUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isFirstTimeUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201602121322039_isFirstTimeUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
