// <auto-generated />
namespace RatiusCommunityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial41));
        
        string IMigrationMetadata.Id
        {
            get { return "201604191438120_initial41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
